# -*- coding: utf-8 -*-

from __future__ import division
import imp
import glob
import os
import shutil
import pandas as pd
import numpy as np


#Type in command Window the main folder containning your 
#CRISPResso_on.. folders

print("Enter your results folder: ")

expFolder =  raw_input()

os.chdir(expFolder)

#Move all html files to a new folder

dirName = 'html'
 
if not os.path.exists(dirName):
    os.mkdir(dirName)
    print("Directory " , dirName ,  " Created ")
else:    
    print("Directory " , dirName ,  " already exists")


if len(glob.glob('*.html'))>0:
    for file in glob.glob('*.html'):
        shutil.move(file,'html')


# glob.glob defines the list of CRISPResso Results subfolders
   
FolderList = glob.glob('CRISP*')

#The next loop iterates the extraction of the following data
#from results files txt that are present in each subfolder:

    #Total aligned reads from the CRISPResso_mapping_statistics.txt

    #The inframe and frameshift mutations reads from Frameshift_analysis.txt

    #Total unModified and modified reads from the 
    #CRISPResso_quantification_of_editing_frequency.txt

FilenameS = 'CRISPResso_mapping_statistics.txt'
FilenameF = 'Frameshift_analysis.txt'
FilenameQ = 'CRISPResso_quantification_of_editing_frequency.txt'


Aligned_reads = []
InFrameMutations = []
FrameshiftMutations = []
UnModified_reads = []
Modified_reads = []

for i in range(0,(len(FolderList))):
    
    os.chdir(FolderList[i])
    
#Depending of the CRISPResso2 analysis output the presence of the 
#results files txt will change.

    # Case1 Successful analysis when coding sequence is provided 
    # to CRISPResso2. All txt files are generated by CRISPResso2.

    if (os.path.exists(FilenameF) and os.path.exists(FilenameS) \
        and os.path.exists(FilenameQ)):

        #pd.read_csv reads the txt files and creates variables containing
        #our values of interest.

        MutationsData = pd.read_csv(FilenameF, sep= ":| ", engine='python')
        
        ReadsData = pd.read_csv(FilenameS, sep="\t")
        
        Editing_Quantification = pd.read_csv(FilenameQ, sep="\t")

        #Append the Alignedreads, UnModified_reads, InFrameMutations, 
        #FrameshiftMutations and Modified reads values obtained through 
        #the for loop.
        
        Aligned_reads.append(ReadsData.iloc[0][2])
        InFrameMutations.append(MutationsData.iloc[1][1])
        FrameshiftMutations.append(MutationsData.iloc[2][1])
        UnModified_reads.append(Editing_Quantification.iloc[0][5])
        Modified_reads.append(Editing_Quantification.iloc[0][6])

        os.chdir("..")
    
    #Case2 Successful analysis when coding sequence is NOT provided to 
    #CRISPResso2. Only CRISPResso_mapping_statistics.txt and 
    #CRISPResso_quantification_of_editing_frequency.txt are generated by
    #CRISPResso2.

    elif (not os.path.exists(FilenameF) and os.path.exists(FilenameS) \
        and os.path.exists(FilenameQ)):

        ReadsData = pd.read_csv(FilenameS, sep="\t")
        
        Editing_Quantification = pd.read_csv(FilenameQ, sep="\t")

        #Append the Alignedreads, UnModified_reads and Modified reads
        #values obtained through the for loop. InFrameMutations and  
        #FrameshiftMutations are appended with NaN because 
        #they are NOT calculated by CRISPResso2.

        Aligned_reads.append(ReadsData.iloc[0][2])
        InFrameMutations.append(np.nan)
        FrameshiftMutations.append(np.nan)
        UnModified_reads.append(Editing_Quantification.iloc[0][5])
        Modified_reads.append(Editing_Quantification.iloc[0][6])
    
        os.chdir("..")
    
    #Case3 NOT Successful analysis. Any of the needed files are generated by 
    #CRISPResso2. Append Alignedreads, UnModified_reads,  
    #Modified_reads, InFrameMutations and FrameshiftMutations with NaN because 
    #in these case they are NOT calculated by CRISPResso.

    else:
    
        Aligned_reads.append(np.nan)
        InFrameMutations.append(np.nan)
        FrameshiftMutations.append(np.nan)
        UnModified_reads.append(np.nan)
        Modified_reads.append(np.nan)
    
        os.chdir("..")

#Calculate Percentage of reads: 
#Un-modified, modified, with Frameshift mutations and with In-Frame mutations.

FS_percentage = []
IF_percentage = []
UnMod_percentage = []
Mod_percentage = []


for i in range(0,(len(FolderList))):
    
    FS_percentage.append\
        (FrameshiftMutations[i] / Aligned_reads[i]*100)
    IF_percentage.append\
        (InFrameMutations[i] / Aligned_reads[i]*100)
    UnMod_percentage.append\
        (UnModified_reads[i] / Aligned_reads[i]*100)
    Mod_percentage.append\
        (Modified_reads[i] / Aligned_reads[i]*100)

#Create dataframe with the generated list of data.

df = pd.DataFrame({'Folder_Sample' : FolderList, \
'Aligned_reads' : Aligned_reads, \
'UnModified_reads' : UnModified_reads, \
'Modified_reads' : Modified_reads, \
'InFrameMutations' : InFrameMutations, \
'FrameshiftMutations' : FrameshiftMutations, \
'Mod_percentage' : Mod_percentage, \
'UnMod_percentage' : UnMod_percentage, \
'FS_percentage' : FS_percentage, \
'IF_percentage' : IF_percentage}) 
    
#Establish the desired order of columns

df = df[['Folder_Sample',\
 'Aligned_reads',\
 'Modified_reads',\
 'UnModified_reads',\
 'InFrameMutations',\
 'FrameshiftMutations',\
 'Mod_percentage',\
 'UnMod_percentage',\
 'FS_percentage',\
 'IF_percentage']]
    
#Export to .csv and xlsx files

os.chdir("..")

try:
    imp.find_module('openpyxl')
    df.to_excel\
        (expFolder + '_POOL.xlsx', float_format="%.2f",na_rep='NaN', \
         index = None)
except ImportError:
        print('If you want an output excel file Install the module openpyxl'\
              ' module by typing\n"pip install openpyxl" '\
                  'in Terminal and run again the script.')

print('\n\nThank you for using CRISPResso2parser_pool.py \n\n'\
      'Enjoy the view of your CRISPResso2 results summary! :)\n\n')

